# top level stuff you probably don't need to touch
highlighter: rouge
markdown: kramdown
permalink: /:title.html
paginate: 5
gems: [jekyll-paginate]
port: 3000
safe: true


# edit here to achieve your personal greatness
url: http://bahusvel.github.io/
baseurl: /
title: Denis Lavrov
author: Denis Lavrov
description: Showcase of the Future
avatar: profile.png
email: bahus.vel@gmail.com
github: bahusvel # username
#twitter: bahusvel
#linkedin: bahusvel
#stackoverflow: bahusvel   #e.g: users/2735833/proton1h1
#Comment out if you don't want disqus 
#disqus: username
#google_analytics: UA-69391421-1


# needed for travis-ci build
exclude: [vendor]
